// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://byseaafzlofytygpyrzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5c2VhYWZ6bG9meXR5Z3B5cnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MzA1MDEsImV4cCI6MjA4NTIwNjUwMX0.apbLAwiWQ0ZjUBYJx3F3mXgfHeo_9e4UOJiOkqVqkq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);